#!/usr/bin/env zsh

if [[ -z "$1" ]]; then
  echo "Error: must specify target file"
  exit 1
fi

case "$1" in
  *.tar.bz2)  tar xjf "$1"      ;;
  *.tar.gz)   tar xzf "$1"      ;;
  *.bz2)      bunzip2 "$1"      ;;
  *.gz)       gunzip "$1"       ;;
  *.tar)      tar xf $1       ;;
  *.tbz2)     tar xjf $1      ;;
  *.tgz)      tar xzf $1      ;;
  *.zip)      unzip $1        ;;
  *.7z)       7z x $1         ;;
  *.rar)      7z x $1         ;;
  *.iso)      7z x $1         ;;
  *.Z)        uncompress $1   ;;
  *)          echo "Error: file '$1' cannot be extracted" ;;
esac
