#!/usr/bin/env zsh

# declare -a args
# declare -A opts
# typeset '@' 'opts'

# zparseopts -D -E -F - a:=arg_val -arg:=arg_val f=flag -flag=flag \
# 	F=foobar -foo=foobar B=foobar -bar=foobar || exit 1

read -r -d '' usage << EOM
Usage: ${funcstack[1]} [options] <filename>

Arguments:
  filename: url of video to download

Options:
  -h, --help              display help for command
EOM

zparseopts -D -E -F - \
  h=help -help=help \
  o:=output -output:=output \
  w:=width -width:=width \
  || exit 1

help=${#help}
output=${output[-1]}
width=${width[-1]}

if [ $help ]; then
  echo $usage
  return
fi

# # [[ -z "$flag_help" ]] || { print -l $usage && return }

# # echo $help
# # echo $output
# # echo $width


# # # Get index of first end of options indicator
# # ((rmidx=$@[(i)(--|-)]))
# # set -- "${@[0,rmidx-1]}" "${@[rmidx+1,-1]}"
# echo $1