#!/usr/bin/env zsh

if [[ -z "$1" ]]; then
  echo "Error: must specify target file"
  exit 1
fi

output=$(identify "$1" 2>&1)
if [ $? -ne 0 ]; then
  echo "$output" 1>&2
  echo "Error: failed to determine image size for file '$1'" 1>&2
  exit $?
fi


width=$(identify -format "%w" "$1")> /dev/null
height=$(identify -format "%h" "$1")> /dev/null
echo "${width}x${height}"
