#!/usr/bin/env zsh

local nvmrc_path
nvmrc_path="$(nvm_find_nvmrc)"

if [ -n "$nvmrc_path" ]; then
  local nvmrc_node_version
  nvmrc_node_version=$(nvm version "$(cat "${nvmrc_path}")")
  if [ "$nvmrc_node_version" != "$(nvm version)" ]; then
    nvm use --silent
  fi
fi
