#!/usr/bin/env zsh

CMD="$1"


if [ -z $CMD ]; then
  echo "Error: No command specified"
  echo "$USAGE"
  return
fi

shift

case "$CMD" in
  info)
    video::info "$@"
    ;;
  optimize)
    video::optimize "$@"
    ;;
  resolution)
    video::resolution "$@"
    ;;
  *)
    echo "Error: Invalid command specified"
    echo "$USAGE"
    ;;
esac
