[".pyenv"]
    url = "https://github.com/pyenv/pyenv/archive/master.tar.gz"
    type = "archive"
    stripComponents = 1
    refreshPeriod = "168h"
[".pyenv/plugins/pyenv-virtualenv"]
    url = "https://github.com/pyenv/pyenv-virtualenv/archive/master.tar.gz"
    type = "archive"
    stripComponents = 1
    refreshPeriod = "168h"
[".nvm"]
    type = "archive"
    url = "https://github.com/nvm-sh/nvm/archive/master.tar.gz"
    stripComponents = 1
    refreshPeriod = "168h"
