---
packages:
- brew: bandwhich
  pacman: bandwhich
- brew: bash
  pacman: ~
- brew: bat
  pacman: bat
- brew: dust
  pacman: dust
- brew: fd
  pacman: fd
- brew: gcc@13
  pacman: ~
- brew: htmlq
  pacman: htmlq
- brew: imagemagick
  pacman: imagemagick
- brew: jless
  pacman: jless
- brew: lsd
  pacman: lsd
- brew: neovim
  pacman: neovim
- brew: p7zip
  pacman: p7zip
- brew: procs
  pacman: procs
- brew: ripgrep
  pacman: ripgrep
- brew: sd
  pacman: sd
- brew: tokei
  pacman: tokei
- brew: webp
  pacman: libwebp
- brew: xsel
  pacman: xsel
- brew: xz
  pacman: xz
- brew: zoxide
  pacman: zoxide

