#!/usr/bin/env zsh

fpath=(~/.zsh/plugins $fpath)

# NAVIGATION
setopt AUTO_PUSHD           # Push the old directory onto the stack on cd.
setopt PUSHD_IGNORE_DUPS    # Do not store duplicates in the stack.
setopt PUSHD_SILENT         # Do not print the directory stack after pushd or popd.
setopt CORRECT              # Spelling correction
setopt EXTENDED_GLOB        # Use extended globbing syntax.

source $DOTFILES/zsh/plugins/bd.zsh

# ACTIVATE PYENV
eval "$(pyenv init -)"
eval "$(pyenv virtualenv-init -)"

# ACTIVATE NVM
source "$NVM_DIR/nvm.sh"

# SOURCE ADDITIONAL CONFIG
for file ($HOME/.zsh/*.zsh); do
    source $file
done

# SOURCE THEME
if [[ $ZSH_VERSION > 5.1 ]]; then
    source ~/.zsh/themes/powerlevel10k/powerlevel10k.zsh-theme
    source ~/.p10k.zsh
fi

# SOURCE 3RD PARTY PLUGINS
source ~/.zsh/plugins/zsh-autosuggestions/zsh-autosuggestions.zsh
source ~/.zsh/plugins/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh
source ~/.zsh/plugins/zsh-history-substring-search/zsh-history-substring-search.zsh

# SOURCE ANY MACHINE-SPECIFIC CONFIG
[[ -f ".zshrc.local" ]] && source .zshrc.local
