#!/usr/bin/env zsh

# ACTIVATE PYENV
eval "$(pyenv init -)"
eval "$(pyenv virtualenv-init -)"

# ACTIVATE NVM
source "$NVM_DIR/nvm.sh"

# SOURCE ADDITIONAL CONFIG
for file ($HOME/.zsh/*.zsh); do
    source $file
done

source ~/.zsh/zsh-autosuggestions/zsh-autosuggestions.zsh
source ~/.zsh/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh
