#!/usr/bin/env zsh

fpath=(~/.zsh/functions ~/.zsh/plugins $fpath)
autoload -Uz $fpath[1]/*(.:t)
zmodload zsh/complist
zmodload zsh/zutil

# NAVIGATION
setopt AUTO_PUSHD           # Push the old directory onto the stack on cd.
setopt PUSHD_IGNORE_DUPS    # Do not store duplicates in the stack.
setopt PUSHD_SILENT         # Do not print the directory stack after pushd or popd.
setopt CORRECT              # Spelling correction
setopt EXTENDED_GLOB        # Use extended globbing syntax.

# HISTORY
setopt EXTENDED_HISTORY          # Write the history file in the ':start:elapsed;command' format.
setopt SHARE_HISTORY             # Share history between all sessions.
setopt HIST_EXPIRE_DUPS_FIRST    # Expire a duplicate event first when trimming history.
setopt HIST_IGNORE_DUPS          # Do not record an event that was just recorded again.
setopt HIST_IGNORE_ALL_DUPS      # Delete an old recorded event if a new event is a duplicate.
setopt HIST_FIND_NO_DUPS         # Do not display a previously found event.
setopt HIST_IGNORE_SPACE         # Do not record an event starting with a space.
setopt HIST_SAVE_NO_DUPS         # Do not write a duplicate event to the history file.
setopt HIST_VERIFY               # Do not execute immediately upon history expansion.

# COMPLETION
bindkey '^[[A' history-search-backward
bindkey '^[[B' history-search-forward

# SOURCE THEME
if [[ $ZSH_VERSION > 5.1 ]]; then
  # Enable Powerlevel10k instant prompt. Should stay close to the top of ~/.zshrc.
  # Initialization code that may require console input (password prompts, [y/n]
  # confirmations, etc.) must go above this block; everything else may go below.
  if [[ -r "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh" ]]; then
    source "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh"
  fi
  source ~/.zsh/themes/powerlevel10k/powerlevel10k.zsh-theme
  source ~/.p10k.zsh
fi

# ALIASES
source ~/.zsh/aliases.zsh
source ~/.zsh/plugins/bd.zsh

# ACTIVATE PYENV
eval "$(pyenv init -)"
eval "$(pyenv virtualenv-init -)"

# ACTIVATE NVM
source "$NVM_DIR/nvm.sh"

# ACTIVATE ZOXIDE
eval "$(zoxide init zsh)"

# SOURCE 3RD PARTY PLUGINS
source ~/.zsh/plugins/zsh-autosuggestions/zsh-autosuggestions.zsh
source ~/.zsh/plugins/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh
source ~/.zsh/plugins/zsh-history-substring-search/zsh-history-substring-search.zsh
source ~/.zsh/plugins/zsh-completions/zsh-completions.plugin.zsh

# LOAD COMPLETIONS
autoload -U compinit
compinit

# SOURCE ANY MACHINE-SPECIFIC CONFIG
[[ -f ".zshrc.local" ]] && source .zshrc.local
