#!/usr/bin/env zsh

# SET BASE DIRECTORY FOR USER FILES
export LOCAL_DIR="$HOME/.local"

# CONFIGURE PATH FOR LOCAL BINARIES
export PATH="$LOCAL_DIR/bin:$PATH"

# RUST
export CARGO_HOME="$HOME/.cargo"
export RUSTUP_HOME="$HOME/.rustup"

# OTHER USER CONFIG
export EDITOR=micro
