#!/usr/bin/env zsh

PYENV_VIRTUALENV_DIR="${PYENV_ROOT}/plugins/pyenv-virtualenv"

# PYENV
if [[ ! -d $PYENV_ROOT ]]; then
  git clone https://github.com/pyenv/pyenv.git $PYENV_ROOT
fi
if [[ ! -d $PYENV_VIRUTALENV_ROOT ]]; then
  git clone https://github.com/pyenv/pyenv-virtualenv.git $PYENV_ROOT
fi





# [".pyenv/plugins/pyenv-virtualenv"]
#     url = "https://github.com/pyenv/pyenv-virtualenv/archive/master.tar.gz"
#     type = "archive"
#     stripComponents = 1
#     refreshPeriod = "168h"
# [".nvm"]
#     type = "archive"
#     url = "https://github.com/nvm-sh/nvm/archive/master.tar.gz"
#     stripComponents = 1
#     refreshPeriod = "168h"
# [".oh-my-zsh"]
#     type = "archive"
#     url = "https://github.com/ohmyzsh/ohmyzsh/archive/master.tar.gz"
#     stripComponents = 1
#     refreshPeriod = "168h"
# [".oh-my-zsh/custom/plugins/zsh-autosuggestions"]
#     type = "archive"
#     url = "https://github.com/zsh-users/zsh-autosuggestions/archive/master.tar.gz"
#     stripComponents = 1
#     refreshPeriod = "168h"
# [".oh-my-zsh/custom/plugins/zsh-syntax-highlighting"]
#     type = "archive"
#     url = "https://github.com/zsh-users/zsh-syntax-highlighting/archive/master.tar.gz"
#     stripComponents = 1
#     refreshPeriod = "168h"
# [".oh-my-zsh/custom/themes/powerlevel10k"]
#     type = "archive"
#     url = "https://github.com/romkatv/powerlevel10k/archive/v1.16.1.tar.gz"
#     stripComponents = 1
