import = ["~/.config/alacritty/themes/tokyo-night.toml"]

[cursor]
style = {shape = "Beam", blinking = "On"}

[env]
TERM = "xterm-256color"

[font]
size = 12
normal.family = "MesloLGS NF"

[scrolling]
history = 100000

[window]
blur = true
decorations = "Full"
opacity = 0.9
option_as_alt = "Both"
padding.x = 4
padding.y = 4
