import = ["~/.config/alacritty/themes/tokyo-night.toml"]

[env]
TERM = "xterm-256color"

[font]
size = 12
normal.family = "MesloLGS NF"

[window]
blur = true
decorations = "Full"
opacity = 0.8
option_as_alt = "Both"
padding.x = 6
padding.y = 6

[cursor]
style = { shape = "Beam", blinking = "On" }

